// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/project-available/available/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/project-available/available/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// BookingTx mocks base method.
func (m *MockStore) BookingTx(arg0 context.Context, arg1 db.BookingTxParams) (db.BookingTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookingTx", arg0, arg1)
	ret0, _ := ret[0].(db.BookingTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookingTx indicates an expected call of BookingTx.
func (mr *MockStoreMockRecorder) BookingTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookingTx", reflect.TypeOf((*MockStore)(nil).BookingTx), arg0, arg1)
}

// CheckBookingOverlap mocks base method.
func (m *MockStore) CheckBookingOverlap(arg0 context.Context, arg1 db.CheckBookingOverlapParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBookingOverlap", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBookingOverlap indicates an expected call of CheckBookingOverlap.
func (mr *MockStoreMockRecorder) CheckBookingOverlap(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBookingOverlap", reflect.TypeOf((*MockStore)(nil).CheckBookingOverlap), arg0, arg1)
}

// CreateAccount mocks base method.
func (m *MockStore) CreateAccount(arg0 context.Context, arg1 db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStoreMockRecorder) CreateAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStore)(nil).CreateAccount), arg0, arg1)
}

// CreateBooking mocks base method.
func (m *MockStore) CreateBooking(arg0 context.Context, arg1 db.CreateBookingParams) (db.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", arg0, arg1)
	ret0, _ := ret[0].(db.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockStoreMockRecorder) CreateBooking(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockStore)(nil).CreateBooking), arg0, arg1)
}

// CreateCustomField mocks base method.
func (m *MockStore) CreateCustomField(arg0 context.Context, arg1 string) (db.CustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomField", arg0, arg1)
	ret0, _ := ret[0].(db.CustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomField indicates an expected call of CreateCustomField.
func (mr *MockStoreMockRecorder) CreateCustomField(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomField", reflect.TypeOf((*MockStore)(nil).CreateCustomField), arg0, arg1)
}

// CreateRoom mocks base method.
func (m *MockStore) CreateRoom(arg0 context.Context, arg1 db.CreateRoomParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockStoreMockRecorder) CreateRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockStore)(nil).CreateRoom), arg0, arg1)
}

// DeleteAccount mocks base method.
func (m *MockStore) DeleteAccount(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockStoreMockRecorder) DeleteAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockStore)(nil).DeleteAccount), arg0, arg1)
}

// DeleteRoom mocks base method.
func (m *MockStore) DeleteRoom(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockStoreMockRecorder) DeleteRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockStore)(nil).DeleteRoom), arg0, arg1)
}

// GetAccount mocks base method.
func (m *MockStore) GetAccount(arg0 context.Context, arg1 string) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockStoreMockRecorder) GetAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockStore)(nil).GetAccount), arg0, arg1)
}

// GetAccountByEmail mocks base method.
func (m *MockStore) GetAccountByEmail(arg0 context.Context, arg1 string) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByEmail indicates an expected call of GetAccountByEmail.
func (mr *MockStoreMockRecorder) GetAccountByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByEmail", reflect.TypeOf((*MockStore)(nil).GetAccountByEmail), arg0, arg1)
}

// GetBookingOfAccount mocks base method.
func (m *MockStore) GetBookingOfAccount(arg0 context.Context, arg1 int64) ([]db.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingOfAccount", arg0, arg1)
	ret0, _ := ret[0].([]db.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingOfAccount indicates an expected call of GetBookingOfAccount.
func (mr *MockStoreMockRecorder) GetBookingOfAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingOfAccount", reflect.TypeOf((*MockStore)(nil).GetBookingOfAccount), arg0, arg1)
}

// GetBookingsOnDate mocks base method.
func (m *MockStore) GetBookingsOnDate(arg0 context.Context, arg1 db.GetBookingsOnDateParams) ([]db.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsOnDate", arg0, arg1)
	ret0, _ := ret[0].([]db.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsOnDate indicates an expected call of GetBookingsOnDate.
func (mr *MockStoreMockRecorder) GetBookingsOnDate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsOnDate", reflect.TypeOf((*MockStore)(nil).GetBookingsOnDate), arg0, arg1)
}

// GetRoom mocks base method.
func (m *MockStore) GetRoom(arg0 context.Context, arg1 int64) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockStoreMockRecorder) GetRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockStore)(nil).GetRoom), arg0, arg1)
}

// ListAccounts mocks base method.
func (m *MockStore) ListAccounts(arg0 context.Context, arg1 db.ListAccountsParams) ([]db.ListAccountsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListAccountsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockStoreMockRecorder) ListAccounts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockStore)(nil).ListAccounts), arg0, arg1)
}

// ListBookings mocks base method.
func (m *MockStore) ListBookings(arg0 context.Context, arg1 db.ListBookingsParams) ([]db.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", arg0, arg1)
	ret0, _ := ret[0].([]db.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockStoreMockRecorder) ListBookings(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockStore)(nil).ListBookings), arg0, arg1)
}

// ListCustomFields mocks base method.
func (m *MockStore) ListCustomFields(arg0 context.Context) ([]db.CustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomFields", arg0)
	ret0, _ := ret[0].([]db.CustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomFields indicates an expected call of ListCustomFields.
func (mr *MockStoreMockRecorder) ListCustomFields(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomFields", reflect.TypeOf((*MockStore)(nil).ListCustomFields), arg0)
}

// ListRoomCustomFieldValues mocks base method.
func (m *MockStore) ListRoomCustomFieldValues(arg0 context.Context, arg1 int64) ([]db.CustomFieldsValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomCustomFieldValues", arg0, arg1)
	ret0, _ := ret[0].([]db.CustomFieldsValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomCustomFieldValues indicates an expected call of ListRoomCustomFieldValues.
func (mr *MockStoreMockRecorder) ListRoomCustomFieldValues(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomCustomFieldValues", reflect.TypeOf((*MockStore)(nil).ListRoomCustomFieldValues), arg0, arg1)
}

// ListRoomCustomFieldValuesBatch mocks base method.
func (m *MockStore) ListRoomCustomFieldValuesBatch(arg0 context.Context, arg1 []int64) ([]db.CustomFieldsValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomCustomFieldValuesBatch", arg0, arg1)
	ret0, _ := ret[0].([]db.CustomFieldsValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomCustomFieldValuesBatch indicates an expected call of ListRoomCustomFieldValuesBatch.
func (mr *MockStoreMockRecorder) ListRoomCustomFieldValuesBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomCustomFieldValuesBatch", reflect.TypeOf((*MockStore)(nil).ListRoomCustomFieldValuesBatch), arg0, arg1)
}

// ListRooms mocks base method.
func (m *MockStore) ListRooms(arg0 context.Context, arg1 db.ListRoomsParams) ([]db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", arg0, arg1)
	ret0, _ := ret[0].([]db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockStoreMockRecorder) ListRooms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockStore)(nil).ListRooms), arg0, arg1)
}

// ListRoomsWithStatus mocks base method.
func (m *MockStore) ListRoomsWithStatus(arg0 context.Context, arg1 db.ListRoomsWithStatusParams) ([]db.ListRoomsWithStatusRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsWithStatus", arg0, arg1)
	ret0, _ := ret[0].([]db.ListRoomsWithStatusRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsWithStatus indicates an expected call of ListRoomsWithStatus.
func (mr *MockStoreMockRecorder) ListRoomsWithStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsWithStatus", reflect.TypeOf((*MockStore)(nil).ListRoomsWithStatus), arg0, arg1)
}

// UpdateAccount mocks base method.
func (m *MockStore) UpdateAccount(arg0 context.Context, arg1 db.UpdateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockStoreMockRecorder) UpdateAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockStore)(nil).UpdateAccount), arg0, arg1)
}

// UpdateBooking mocks base method.
func (m *MockStore) UpdateBooking(arg0 context.Context, arg1 db.UpdateBookingParams) (db.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", arg0, arg1)
	ret0, _ := ret[0].(db.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockStoreMockRecorder) UpdateBooking(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockStore)(nil).UpdateBooking), arg0, arg1)
}

// UpdateCustomFieldShown mocks base method.
func (m *MockStore) UpdateCustomFieldShown(arg0 context.Context, arg1 db.UpdateCustomFieldShownParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomFieldShown", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomFieldShown indicates an expected call of UpdateCustomFieldShown.
func (mr *MockStoreMockRecorder) UpdateCustomFieldShown(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomFieldShown", reflect.TypeOf((*MockStore)(nil).UpdateCustomFieldShown), arg0, arg1)
}

// UpdateRoom mocks base method.
func (m *MockStore) UpdateRoom(arg0 context.Context, arg1 db.UpdateRoomParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoom indicates an expected call of UpdateRoom.
func (mr *MockStoreMockRecorder) UpdateRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoom", reflect.TypeOf((*MockStore)(nil).UpdateRoom), arg0, arg1)
}

// UpsertRoomCustomFieldValue mocks base method.
func (m *MockStore) UpsertRoomCustomFieldValue(arg0 context.Context, arg1 db.UpsertRoomCustomFieldValueParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRoomCustomFieldValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRoomCustomFieldValue indicates an expected call of UpsertRoomCustomFieldValue.
func (mr *MockStoreMockRecorder) UpsertRoomCustomFieldValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRoomCustomFieldValue", reflect.TypeOf((*MockStore)(nil).UpsertRoomCustomFieldValue), arg0, arg1)
}
