// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, role, email, password, phone, student_id)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, role, email, password, phone, student_id, is_delete
`

type CreateAccountParams struct {
	Name      string `json:"name"`
	Role      string `json:"role"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Phone     string `json:"phone"`
	StudentID string `json:"student_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.StudentID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
UPDATE accounts
SET is_delete = true
WHERE id = $1
AND is_delete != true
RETURNING id, name, role, email, password, phone, student_id, is_delete
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, deleteAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, role, email, password, phone, student_id, is_delete FROM accounts WHERE id = $1 AND is_delete != true
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, role, email, password, phone, student_id, is_delete FROM accounts WHERE is_delete != true LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.StudentID,
			&i.IsDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, role = $3, email = $4, password = $5, phone = $6, student_id = $7
WHERE id = $1
AND is_delete != true
RETURNING id, name, role, email, password, phone, student_id, is_delete
`

type UpdateAccountParams struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Phone     string `json:"phone"`
	StudentID string `json:"student_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.StudentID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}
