// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, role, email, hashed_password, phone, student_id)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, role, email, hashed_password, phone, student_id, is_delete
`

type CreateAccountParams struct {
	Name           string `json:"name"`
	Role           string `json:"role"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
	Phone          string `json:"phone"`
	StudentID      string `json:"student_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.HashedPassword,
		arg.Phone,
		arg.StudentID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET is_delete = true
WHERE student_id = $1
AND is_delete != true
`

func (q *Queries) DeleteAccount(ctx context.Context, studentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, studentID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, role, email, hashed_password, phone, student_id, is_delete FROM accounts WHERE student_id = $1 AND is_delete != true
`

func (q *Queries) GetAccount(ctx context.Context, studentID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, studentID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, role, email, phone, student_id FROM accounts WHERE is_delete != true LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAccountsRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	StudentID string `json:"student_id"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.StudentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, phone = $3
WHERE id = $1
AND is_delete != true
RETURNING id, name, role, email, hashed_password, phone, student_id, is_delete
`

type UpdateAccountParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.ID, arg.Name, arg.Phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.StudentID,
		&i.IsDelete,
	)
	return i, err
}
