// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_field.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createCustomField = `-- name: CreateCustomField :one
INSERT INTO "custom_fields" ("key")
VALUES ($1)
RETURNING id, key, shown
`

func (q *Queries) CreateCustomField(ctx context.Context, key string) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, createCustomField, key)
	var i CustomField
	err := row.Scan(&i.ID, &i.Key, &i.Shown)
	return i, err
}

const listCustomFields = `-- name: ListCustomFields :many
SELECT id, key, shown FROM "custom_fields"
ORDER BY "key"
`

func (q *Queries) ListCustomFields(ctx context.Context) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomField{}
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(&i.ID, &i.Key, &i.Shown); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomCustomFieldValues = `-- name: ListRoomCustomFieldValues :many
SELECT id, room_id, customfield_id, value FROM "custom_fields_value"
WHERE room_id = $1
`

func (q *Queries) ListRoomCustomFieldValues(ctx context.Context, roomID int64) ([]CustomFieldsValue, error) {
	rows, err := q.db.QueryContext(ctx, listRoomCustomFieldValues, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFieldsValue{}
	for rows.Next() {
		var i CustomFieldsValue
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CustomfieldID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomCustomFieldValuesBatch = `-- name: ListRoomCustomFieldValuesBatch :many
SELECT id, room_id, customfield_id, value FROM "custom_fields_value"
WHERE room_id = ANY($1::bigint[])
`

func (q *Queries) ListRoomCustomFieldValuesBatch(ctx context.Context, dollar_1 []int64) ([]CustomFieldsValue, error) {
	rows, err := q.db.QueryContext(ctx, listRoomCustomFieldValuesBatch, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFieldsValue{}
	for rows.Next() {
		var i CustomFieldsValue
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CustomfieldID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomFieldShown = `-- name: UpdateCustomFieldShown :exec
UPDATE "custom_fields"
SET "key" = $2, shown = $3
WHERE id = $1
`

type UpdateCustomFieldShownParams struct {
	ID    int64  `json:"id"`
	Key   string `json:"key"`
	Shown bool   `json:"shown"`
}

func (q *Queries) UpdateCustomFieldShown(ctx context.Context, arg UpdateCustomFieldShownParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomFieldShown, arg.ID, arg.Key, arg.Shown)
	return err
}

const upsertRoomCustomFieldValue = `-- name: UpsertRoomCustomFieldValue :exec
INSERT INTO "custom_fields_value" (room_id, customfield_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, customfield_id) DO UPDATE SET value = EXCLUDED.value
`

type UpsertRoomCustomFieldValueParams struct {
	RoomID        int64  `json:"room_id"`
	CustomfieldID int64  `json:"customfield_id"`
	Value         string `json:"value"`
}

func (q *Queries) UpsertRoomCustomFieldValue(ctx context.Context, arg UpsertRoomCustomFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoomCustomFieldValue, arg.RoomID, arg.CustomfieldID, arg.Value)
	return err
}
