// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Role      string       `json:"role"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Phone     string       `json:"phone"`
	StudentID string       `json:"student_id"`
	IsDelete  sql.NullBool `json:"is_delete"`
}

type Booking struct {
	ID           int64          `json:"id"`
	AccountID    int64          `json:"account_id"`
	RoomID       int64          `json:"room_id"`
	Start        time.Time      `json:"start"`
	End          time.Time      `json:"end"`
	Status       sql.NullString `json:"status"`
	PhoneBooking string         `json:"phone_booking"`
}

type Customfield struct {
	ID     int64        `json:"id"`
	RoomID int64        `json:"room_id"`
	Value  string       `json:"value"`
	Shown  sql.NullBool `json:"shown"`
}

type Room struct {
	ID int64 `json:"id"`
	// H1-100
	Location string       `json:"location"`
	Name     string       `json:"name"`
	Image    string       `json:"image"`
	IsDelete sql.NullBool `json:"is_delete"`
}
