// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	create_account(ctx context.Context, arg create_accountParams) (Account, error)
	delete_account(ctx context.Context, id int64) (Account, error)
	get_account(ctx context.Context, id int64) (Account, error)
	list_accounts(ctx context.Context, arg list_accountsParams) ([]Account, error)
	update_account(ctx context.Context, arg update_accountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
