// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CheckBookingOverlap(ctx context.Context, arg CheckBookingOverlapParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateCustomField(ctx context.Context, key string) (CustomField, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeleteAccount(ctx context.Context, studentID string) error
	DeleteRoom(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, studentID string) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetBookingOfAccount(ctx context.Context, accountID int64) ([]Booking, error)
	GetBookingsOnDate(ctx context.Context, arg GetBookingsOnDateParams) ([]Booking, error)
	GetRoom(ctx context.Context, id int64) (Room, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error)
	ListCustomFields(ctx context.Context) ([]CustomField, error)
	ListRoomCustomFieldValues(ctx context.Context, roomID int64) ([]CustomFieldsValue, error)
	ListRoomCustomFieldValuesBatch(ctx context.Context, dollar_1 []int64) ([]CustomFieldsValue, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	ListRoomsWithStatus(ctx context.Context, arg ListRoomsWithStatusParams) ([]ListRoomsWithStatusRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error)
	UpdateCustomFieldShown(ctx context.Context, arg UpdateCustomFieldShownParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpsertRoomCustomFieldValue(ctx context.Context, arg UpsertRoomCustomFieldValueParams) error
}

var _ Querier = (*Queries)(nil)
