// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, location, image)
VALUES ($1,$2,$3)
RETURNING id, location, name, image, is_delete
`

type CreateRoomParams struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Image    string `json:"image"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.Name, arg.Location, arg.Image)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Image,
		&i.IsDelete,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
UPDATE rooms
SET is_delete = true
WHERE id = $1
AND is_delete != true
RETURNING id, location, name, image, is_delete
`

func (q *Queries) DeleteRoom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, location, name, image, is_delete FROM rooms
WHERE id = $1
AND is_delete != true
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Image,
		&i.IsDelete,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, location, name, image, is_delete FROM rooms
WHERE is_delete != true
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Location,
			&i.Name,
			&i.Image,
			&i.IsDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $2, location = $3, image = $4
WHERE id = $1
AND is_delete != true
RETURNING id, location, name, image, is_delete
`

type UpdateRoomParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
	Image    string `json:"image"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Image,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Image,
		&i.IsDelete,
	)
	return i, err
}
