// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package db

import (
	"context"
	"time"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, location, image)
VALUES ($1,$2,$3)
RETURNING id, location, name, image, is_delete
`

type CreateRoomParams struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Image    string `json:"image"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.Name, arg.Location, arg.Image)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Image,
		&i.IsDelete,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
UPDATE rooms
SET is_delete = true
WHERE id = $1
AND is_delete != true
RETURNING id, location, name, image, is_delete
`

func (q *Queries) DeleteRoom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, location, name, image, is_delete FROM rooms
WHERE id = $1
AND is_delete != true
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Image,
		&i.IsDelete,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, location, name, image, is_delete FROM rooms
WHERE is_delete != true
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Location,
			&i.Name,
			&i.Image,
			&i.IsDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsWithStatus = `-- name: ListRoomsWithStatus :many
SELECT
    r.id,
    r.location,
    r.name,
    r.image,
    r.is_delete,
    COALESCE(BOOL_OR(
        $1 >= b.start
        AND $1 < b.end
    ), FALSE) AS is_occupied_now,
    MAX(
        CASE
            WHEN $1 >= b.start AND $1 < b.end AND b.status = 'confirmed'
            THEN b.end
        END
    ) AS occupied_until
FROM rooms r
LEFT JOIN bookings b
    ON b.room_id = r.id
    AND $1 >= b.start
    AND $1 < b.end
    AND b.status = 'confirmed'
GROUP BY r.id
ORDER BY r.id
LIMIT $2 OFFSET $3
`

type ListRoomsWithStatusParams struct {
	Start  time.Time `json:"start"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListRoomsWithStatusRow struct {
	ID            int64       `json:"id"`
	Location      string      `json:"location"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	IsDelete      bool        `json:"is_delete"`
	IsOccupiedNow interface{} `json:"is_occupied_now"`
	OccupiedUntil interface{} `json:"occupied_until"`
}

func (q *Queries) ListRoomsWithStatus(ctx context.Context, arg ListRoomsWithStatusParams) ([]ListRoomsWithStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsWithStatus, arg.Start, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsWithStatusRow{}
	for rows.Next() {
		var i ListRoomsWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Location,
			&i.Name,
			&i.Image,
			&i.IsDelete,
			&i.IsOccupiedNow,
			&i.OccupiedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $2, location = $3, image = $4
WHERE id = $1
AND is_delete != true
RETURNING id, location, name, image, is_delete
`

type UpdateRoomParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
	Image    string `json:"image"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Image,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Name,
		&i.Image,
		&i.IsDelete,
	)
	return i, err
}
